import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer1 from "@/components/Footer1";
import { Providers } from "./Features/Provider";
import BottomNavi from "@/components/ui/BottomNavi";
import Layout from "./Features/LoginLayout";
import { AuthProvider } from "./Features/authProvider";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
         <AuthProvider>
          <Layout>
            {children}
            <div className="sm:hidden">
              <BottomNavi />
            </div>
          </Layout>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
